// flow-typed signature: 3e729a481e2c491f65cdf1b29ba369c2
// flow-typed version: <<STUB>>/inline-source-map_v^0.6.2/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inline-source-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inline-source-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inline-source-map/example/foo-bar' {
  declare module.exports: any;
}

declare module 'inline-source-map/test/inline-source-map' {
  declare module.exports: any;
}

declare module 'inline-source-map/test/source-content' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inline-source-map/example/foo-bar.js' {
  declare module.exports: $Exports<'inline-source-map/example/foo-bar'>;
}
declare module 'inline-source-map/index' {
  declare module.exports: $Exports<'inline-source-map'>;
}
declare module 'inline-source-map/index.js' {
  declare module.exports: $Exports<'inline-source-map'>;
}
declare module 'inline-source-map/test/inline-source-map.js' {
  declare module.exports: $Exports<'inline-source-map/test/inline-source-map'>;
}
declare module 'inline-source-map/test/source-content.js' {
  declare module.exports: $Exports<'inline-source-map/test/source-content'>;
}
